# syntax=docker/dockerfile:1.0.0-experimental
FROM continuumio/miniconda3

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV HOME=/root
WORKDIR $HOME

COPY notebooks/ $HOME/notebooks/
COPY environment.yml $HOME/environment.reproduce.yml
RUN conda env update -f $HOME/environment.reproduce.yml

RUN apt-get update && apt-get -y install gcc
RUN pip install --upgrade jupyter mxnet==1.4.1 gluonts
